# Copyright(C) 2018 CERN.

# Invenio-Records-Editor
# is free software; you can redistribute it and / or modify
# it under the terms of the MIT License; see LICENSE file for more details.

notifications:
  email: false

sudo: false

language: node_js

node_js:
  - 10.6.0

cache:
  directories:
    - node_modules

env:
  global:
    - GH_REF: 'github.com/inveniosoftware/invenio-records-editor-js.git'
    - secure: 'mnlQlai+1QH0aAerVpoH97wxzoNgaEZnl4s6XajIUsnhy4IjnqFa7iB83rNniSapPk5RiEGB1C549aw7LtkL9ERRzMk4T3dqukFU0DRES5+4E115RgDvMN9Jd35MvFfyIeplMHm94cVu/+kmZSGzmaCItGCvC2cNYJ2DdYz3pzL8Pt9DZ8PJ0XS9N6dOi/1yAeWnEPFdiwBgCwKBtvH9a/Kz4YxkIdMlTwPl4kCBFWotiwj1cxLY5KxSW4cCAeavux2cLyrY6QIXV6Wj3UUw1DBOnao0QFiBmKmoYrNLScJffYj5DGn06F8VOIvolK9X2/XvbghSCmiqcRMEvOtsACJWTs1k039UfYvjMnhWDpbeKwXMHK2OD0BAa/3+dqYOWKaVem/RN1HJkzd0fz2aiP9KMgfQTGfF/BzgUERZfU9S/9FomUrzHCz+cs5Yc1PKe8FAvQoyGu5pnMA101cr4o17+TUAPUjRYHUUTK+/xca7h/B8cATyWQOR7/o5/L+MTwyjwdVAj14bSJa+VWnBU+EN15jubbZ+kkVpYBSIDfrrdU6yROUX6zMxZS0vomUwHDjLE9fR8cKZZu4JdYm0cMvMMrFDSimrGJuUvdoRWJQtYFDYg1xDxQFe/6layr7ZNpqFfbRosdofzlEyA1APSmIvJrQzJ/Sl5m405od1GOE='

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm i

script:
  - npm run-script test

before_deploy:
  - npm run-script build

deploy:
  provider: npm
  skip_cleanup: true
  email: info@inveniosoftware.org
  api_key:
    secure: UT7NNFeh44SPUTThZu44fHj2aj1+U8GRrLkI0nRrGLQlk243417lNGy9+nkEhwYx+tdoQPK+euFuA3uKJxPnR8lf64CrALkIdTkDRB7/9QgyceGU38l0MpxBh/SlRBkUIuxebnR9ktARX5o8QO+1UsgATlwx8j+nvtBs1RoVxIZmlvHSx4Aga+9VnYzsH7TZTv7emYoICeKKbEG68c+oyzEUG6AOrY2rK6zv/vczES2i0aco0z6Vh6R+gU/PsSzuNoN5lCZ7s90gCkUMNL0Jbtz3VrT7+UNkALXlZxdFw/ffxmJqnP788NYTfy8iLfFnhsWXi2bxvKU8BpCLXRSRijPF6hiBE5mfWX6o79DE+ipVlX5AvGZkXYpWMQ/kDmCIZuidPqVb5P7+HZQze72ZNa9Wg/crwbTDY9CX2qfEiGMB1O3e5mP0ZA/gfh5qHBElj4cl551q/2y5t40cRWl3+tKWcvbbo4O6sIA2vZWP4TWD2E3L/k6XEzyFCbqrNdBgBQ3t4P0v6MKZ5zIrIDuECVXiR01goKalxw+nUGUeBWnma4oEU4vlgw55pZbyI9WZDGgY1t17myLjf317U463ijeY1k2MjF6rKTTWH/Ea66uHCv8lw3+8Ak5do0dqkGM45bLG9c7cjFZ6NOhJWSnq/xnReDXoh9+R6aVvgHZu3XU=
  on:
    tags: true
    repo: inveniosoftware/invenio-records-editor-js
    branch: master
    node: 10.6.0
